package com.nightpower.demo.model.db;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DemoTranLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_tran_log.tran_seq
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private String tranSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_tran_log.tran_date
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private String tranDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_tran_log.tran_time
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private Date tranTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_tran_log.tran_amount
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private BigDecimal tranAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_tran_log.tran_code
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private String tranCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_tran_log.tran_name
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private String tranName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_tran_log.tran_desc
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private String tranDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_tran_log.tran_seq
     *
     * @return the value of demo_tran_log.tran_seq
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public String getTranSeq() {
        return tranSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_tran_log.tran_seq
     *
     * @param tranSeq the value for demo_tran_log.tran_seq
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public void setTranSeq(String tranSeq) {
        this.tranSeq = tranSeq == null ? null : tranSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_tran_log.tran_date
     *
     * @return the value of demo_tran_log.tran_date
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public String getTranDate() {
        return tranDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_tran_log.tran_date
     *
     * @param tranDate the value for demo_tran_log.tran_date
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public void setTranDate(String tranDate) {
        this.tranDate = tranDate == null ? null : tranDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_tran_log.tran_time
     *
     * @return the value of demo_tran_log.tran_time
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public Date getTranTime() {
        return tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_tran_log.tran_time
     *
     * @param tranTime the value for demo_tran_log.tran_time
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public void setTranTime(Date tranTime) {
        this.tranTime = tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_tran_log.tran_amount
     *
     * @return the value of demo_tran_log.tran_amount
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public BigDecimal getTranAmount() {
        return tranAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_tran_log.tran_amount
     *
     * @param tranAmount the value for demo_tran_log.tran_amount
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public void setTranAmount(BigDecimal tranAmount) {
        this.tranAmount = tranAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_tran_log.tran_code
     *
     * @return the value of demo_tran_log.tran_code
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public String getTranCode() {
        return tranCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_tran_log.tran_code
     *
     * @param tranCode the value for demo_tran_log.tran_code
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public void setTranCode(String tranCode) {
        this.tranCode = tranCode == null ? null : tranCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_tran_log.tran_name
     *
     * @return the value of demo_tran_log.tran_name
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public String getTranName() {
        return tranName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_tran_log.tran_name
     *
     * @param tranName the value for demo_tran_log.tran_name
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public void setTranName(String tranName) {
        this.tranName = tranName == null ? null : tranName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_tran_log.tran_desc
     *
     * @return the value of demo_tran_log.tran_desc
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public String getTranDesc() {
        return tranDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_tran_log.tran_desc
     *
     * @param tranDesc the value for demo_tran_log.tran_desc
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    public void setTranDesc(String tranDesc) {
        this.tranDesc = tranDesc == null ? null : tranDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DemoTranLog other = (DemoTranLog) that;
        return (this.getTranSeq() == null ? other.getTranSeq() == null : this.getTranSeq().equals(other.getTranSeq()))
            && (this.getTranDate() == null ? other.getTranDate() == null : this.getTranDate().equals(other.getTranDate()))
            && (this.getTranTime() == null ? other.getTranTime() == null : this.getTranTime().equals(other.getTranTime()))
            && (this.getTranAmount() == null ? other.getTranAmount() == null : this.getTranAmount().equals(other.getTranAmount()))
            && (this.getTranCode() == null ? other.getTranCode() == null : this.getTranCode().equals(other.getTranCode()))
            && (this.getTranName() == null ? other.getTranName() == null : this.getTranName().equals(other.getTranName()))
            && (this.getTranDesc() == null ? other.getTranDesc() == null : this.getTranDesc().equals(other.getTranDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTranSeq() == null) ? 0 : getTranSeq().hashCode());
        result = prime * result + ((getTranDate() == null) ? 0 : getTranDate().hashCode());
        result = prime * result + ((getTranTime() == null) ? 0 : getTranTime().hashCode());
        result = prime * result + ((getTranAmount() == null) ? 0 : getTranAmount().hashCode());
        result = prime * result + ((getTranCode() == null) ? 0 : getTranCode().hashCode());
        result = prime * result + ((getTranName() == null) ? 0 : getTranName().hashCode());
        result = prime * result + ((getTranDesc() == null) ? 0 : getTranDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tranSeq=").append(tranSeq);
        sb.append(", tranDate=").append(tranDate);
        sb.append(", tranTime=").append(tranTime);
        sb.append(", tranAmount=").append(tranAmount);
        sb.append(", tranCode=").append(tranCode);
        sb.append(", tranName=").append(tranName);
        sb.append(", tranDesc=").append(tranDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}