package com.nightpower.demo.dao;

import com.nightpower.demo.model.db.DemoTranLog;

public interface DemoTranLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    int deleteByPrimaryKey(String tranSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    int insert(DemoTranLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    int insertSelective(DemoTranLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    DemoTranLog selectByPrimaryKey(String tranSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    int updateByPrimaryKeySelective(DemoTranLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_tran_log
     *
     * @mbg.generated Sat Jan 04 22:25:44 CST 2020
     */
    int updateByPrimaryKey(DemoTranLog record);
}